# -*- coding: utf-8 -*-
"""Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OUrp5K3wZ9sU1-JQN2V8C0VkvDQX9bzt

**Prediksi Nilai Akhir Siswa Menggunakan Algoritma Artificial Neural Network dan Random Forest**
"""

# ============================================================
# 1. IMPORT LIBRARY
# ============================================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# ANN
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

# Random Forest
from sklearn.ensemble import RandomForestRegressor

# Save model
import joblib

uploaded = files.upload()

df = pd.read_csv("student-mat.csv", sep=";")
df.head()

df_encoded = pd.get_dummies(df, drop_first=True)
df_encoded.head()

X = df_encoded.drop("G3", axis=1)
y = df_encoded["G3"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model_ann = Sequential([
    Dense(128, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dropout(0.2),
    Dense(64, activation='relu'),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(1)
])

model_ann.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

model_ann.summary()

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=15,
    restore_best_weights=True
)

history = model_ann.fit(
    X_train_scaled, y_train,
    validation_split=0.2,
    epochs=300,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

plt.figure(figsize=(8,5))
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.legend()
plt.title("ANN Loss Curve")
plt.show()

rf_model = RandomForestRegressor(
    n_estimators=300,
    max_depth=None,
    random_state=42
)

rf_model.fit(X_train, y_train)

# ANN
y_pred_ann = model_ann.predict(X_test_scaled)

# Random Forest
y_pred_rf = rf_model.predict(X_test)

def evaluate_model(name, y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)

    print(f"\n===== Evaluasi Model: {name} =====")
    print(f"MAE  : {mae:.4f}")
    print(f"MSE  : {mse:.4f}")
    print(f"RMSE : {rmse:.4f}")
    print(f"R²    : {r2:.4f}")

evaluate_model("ANN", y_test, y_pred_ann)
evaluate_model("Random Forest", y_test, y_pred_rf)

importances = rf_model.feature_importances_
indices = np.argsort(importances)[::-1]

plt.figure(figsize=(12,6))
plt.title("Feature Importance - Random Forest")
plt.bar(range(X.shape[1]), importances[indices])
plt.xticks(range(X.shape[1]), X.columns[indices], rotation=90)
plt.tight_layout()
plt.show()

model_ann.save("model_ann_student_mat.h5")
print("Model ANN berhasil disimpan sebagai model_ann_student_mat.h5")

joblib.dump(rf_model, "random_forest_student_mat.pkl")
print("Model Random Forest berhasil disimpan sebagai random_forest_student_mat.pkl")

import joblib
joblib.dump(scaler, "scaler.pkl")